### ISSUE TITLE
NDI output won't display on Raspberry OS buster

### ISSUE THREAD

**Issue by lapoule** [melnijir/Dicaffeine#13]
Hello,

I'm facing an issue on my newly bought Raspberry Pi 400.

I just installed dicaffeine on my computer as mentioned on the installation page.
https://dicaffeine.com/raspbian

The web browser opens correctly and gives me the password field. I fill it and get to the simple player display as shown on your video :
https://www.youtube.com/watch?v=_xC_zB6dlks&t=96s

However when I select an output and click play, the message "player is running, stop it first" displays, but immediately after nothing happens, I'm back to the player menu. I tried twice, on 2 NDI devices, on 2 separate networks.

I checked the Internet and tried the debug command "yuri2 /tmp/yuri_config_player.xml" but it fails due to a missing shared library "libboost-program-options.so.1.74.0".
I tried updating this library but the latest version available on buster is 1.67.0.
I tried to update yuri2, reinstall it separately from scratch with latest version, but it still doesn't work.

Could you please have an eye on this, and maybe update the yuri2 version dependency for dicaffeine so it can work on buster ?

At then moment I'm upgrading to bullseye, hope it'll work...
Thank you.

Sincerely,
Anthony

**Comment by melnijir** [comment]
Hi Anthony,
Buster release is no longer supported, please use the newer Bullseye. If you'll need it on Buster, you can use the older releases, installation should be described here: https://dicaffeine.com/raspbian

Best regards,
Jiri

**Comment by lapoule** [comment]
Hello,

Thanks for your answer. I see you have updated the FAQ on your website.
Dicaffeine works like a charm on Bullseye.
Keep up the good work !

Sincerely,
Anthony

**Comment by yiids** [comment]
Im having this exact seem problem on raspbian bullseye, with bullseye dicaffeine repo. From one day to another, I cant start NDI streams and get the message "player is running, stop it first"
ii  dicaffeine                             0.6.3                            arm64        dicaffeine built using CMake

**Comment by cmwoodman** [comment]
seeing the same thing on bookworm

dicaffeine 0.6.3
raspberry pi4 8gb

**Comment by prometheushookup** [comment]
Hi there. Just tried installing Dicaffeine 0.7.5 on the Raspberry Pi Trixie version.

Everything installs fine, but I get the exact same issues as in this thread. 

Any chance to look at it? :-)

Raspberry Pi 5 8gb

Cheers
