### ISSUE TITLE
DiCaffeine and NDI Support?

### ISSUE THREAD

**Issue by spegis** [melnijir/Dicaffeine#17]
Apologies for asking here if it is the wrong place to do so, does DiCaffeine support NDI 5? I am working with ZoomISO on a Macbook Pro M1 Max and wondering if the NID 5 (M1 Natives) or NDI 4 (M1 Rosetta) is the version I should run if I am sending to DiCaffiene Pi's feeding an ATEM.

**Comment by melnijir** [comment]
Hi, yes, the Dicaffeine is using NDI 5. :wink:
