### ISSUE TITLE
Latest RPI images

### ISSUE THREAD

**Issue by Rhidalin-Bytes** [melnijir/Dicaffeine#26]
I have tried several methods of installing the package. However, I am getting a certificate error related to the package. [trusted source] in repo line helps slightly but arm/h packages still throws a hard ca expiration error. I ensured that all ppa's were up to date for both buster and bullseye and got the same error.

**Comment by melnijir** [comment]
Should be already fixed.

**Comment by koensayr** [comment]
Looks like I'm getting this error again, worth a reopen?

firefly@firefly:~$ sudo apt-get update
Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
Ign:2 https://dicaffeine.com/repository bionic InRelease                                                                           
Err:4 https://dicaffeine.com/repository bionic Release                                                                             
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.8.165.12 443]
Hit:5 http://mirrors.aliyun.com/ubuntu-ports bionic InRelease        
Hit:6 http://mirrors.aliyun.com/ubuntu-ports bionic-updates InRelease          
Hit:3 https://wiki.t-firefly.com/firefly-rk3399-repo bionic InRelease                                 
Hit:7 http://mirrors.aliyun.com/ubuntu-ports bionic-backports InRelease                               
Hit:8 http://mirrors.aliyun.com/ubuntu-ports bionic-security InRelease         
Reading package lists... Done
E: The repository 'https://dicaffeine.com/repository bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
