### ISSUE TITLE
Dicaffeine seems to be offline

### ISSUE THREAD

**Issue by burtmacklin16** [melnijir/Dicaffeine#29]
Attempting to install Dicaffeine on a RaspberryPi 2 results in the following error when entering the web UI:

![image](https://user-images.githubusercontent.com/38384310/169103791-0a697439-0640-4063-bf30-5268388f40d4.png)

Installation completed successfully, however the Player, Streamer, Control, and System pages all yield this error followed by a redirect to the login page.

**Comment by melnijir** [comment]
Hi, you can try the latests release with the latest Raspbian distro, but sadly, the Raspberry 2 is not supported anymore.
