### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by zubeue** [melnijir/Dicaffeine#34]
Hi,
I just installed version 0.6.2 of dicaffeine on a raspberry pi 4. The installation went OK, but I cannot login to the dserver. There is no file /etc/dicaffeine/dauth.json. 
Thank you for your help and the software.
Regards Ueli

**Comment by melnijir** [comment]
The file `/etc/dicaffeine/dauth.json` is only generated when you'll change the password from the default **admin**.
