### ISSUE TITLE
NDI source not present

### ISSUE THREAD

**Issue by andrej360vpk** [melnijir/Dicaffeine#36]
I have installed Dicaffeine software and could select NDI source as there is non on the list.
I have tried to change IP address in configuration, but no success.
We have NDI access manager to control NDI streams on the network and maybe this is the reason?

**Comment by melnijir** [comment]
Hi, that could be the reason. Dicaffeine uses for searching the official NDI library, if if won't see the sources there wouldn't be any listed.
