### ISSUE TITLE
Media in Media player

### ISSUE THREAD

**Issue by jbonde** [melnijir/Dicaffeine#43]
Hi - I can't select a media to playback in the Media Player. The drop down box is not working as for the other options.
I am using a RPi4 with updated OS

**Comment by melnijir** [comment]
Media needs to be saved into your home folder:

~/Dicaffeine/media

Then push the "Reload media" button and select the right file.

**Comment by jbonde** [comment]
It doesn't work. Uploaded a media to the folder and it doesn't show in the drop down even after clicking "Reload Media"

**Comment by jbonde** [comment]
It seems like it is related to type of media. Could be useful to specify which media types are supported (only mpg?)

**Comment by melnijir** [comment]
You're right, I though it's already there but apparently not. :) Currently supported file extensions are mp4, avi and mkv. I'll add these to the description.

**Comment by jbonde** [comment]
Thanks! Would also be nice if you could give some recommendations in terms of file properties (bitrate, size, GOP, image size etc) that is suitable for RPi4 playback.
