### ISSUE TITLE
Debian 12 Bookworm x86_64 support

### ISSUE THREAD

**Issue by ogmkp** [melnijir/Dicaffeine#49]
Hi, thanks for this project.

I'm trying to get it working on a Debian 12 for x86_64, all packages from the ubuntu jammy repo installs, but I have a yuri2 issue who deny dicaffeine player to run:

```
ERROR 1: 02:10:53 [XmlBuilder] Failed to load file /tmp/yuri_config_player.xml
FATAL ERROR 0: 02:10:53 [YURI2] failed to initialize application: Failed to load file /tmp/yuri_config_player.xml
```

After little dependency research:
```
$ ldd /usr/lib/yuri2/yuri* | grep -i "not found"
	libavformat.so.58 => not found
	libswscale.so.5 => not found
	libavcodec.so.58 => not found
	libjpeg.so.8 => not found
	libavformat.so.58 => not found
	libavcodec.so.58 => not found
	libx264.so.163 => not found
```

Debian stable main repo contains libavformat59, libavcodec59, libavformat59, libswscale6, libx264-164.

It will be great if you can make a Debian 12 version of Dicaffeine to support the best Linux distro with 2 - 5 year maintenance with a solution for theses 7 missing dependencies :+1: 

Thank you !

**Comment by DanceMore** [comment]
I'm currently trying to install Dicaffeine on Debian12 and landed here looking for source code to attempt to build it myself if needed ....

**Comment by ogmkp** [comment]
Hi @melnijir do you have news ?
In the meantime, I'm testing on ubuntu 22.04.

**Comment by melnijir** [comment]
Hi, I've prepared the packages for Debian12 on Intel/AMD platforms:
https://dicaffeine.com/_media/bin:bookworm:amd64:yuri2-2.8.0-1587-debian-12-linux.deb
https://dicaffeine.com/_media/bin:bookworm:amd64:dicaffeine-0.7.3-linux.deb

After the successful installation please run automatic script to download the NDI libraries:
`sudo dicaffeine_get_ndi5 install x86_64-linux-gnu`

The packages are **untested**, so I am not sure if everything works as it should. I'll do more extensive tests later.

PS: user has to be allowed to use sudo :wink:

**Comment by johnthq** [comment]
gave  your deb packages a try. 

$ yuri2 -I ndi_input
ERROR 1: 18:34:17 [XmlBuilder] Failed to load file
No input thread found for ndi_input

**Comment by johnthq** [comment]
testing these .deb packages now. 
i had to sudo ln -s /usr/lib/firefox /opt/firefox 

and a quick port change to `/etc/dicaffeine/dserver.json` because i use nginxproxymanager and im up and running

**Comment by ogmkp** [comment]
I'm closing this ticket, thank you.

**Comment by jacobroufa** [comment]
> Hi, I've prepared the packages for Debian12 on Intel/AMD platforms: https://dicaffeine.com/_media/bin:bookworm:amd64:yuri2-2.8.0-1587-debian-12-linux.deb https://dicaffeine.com/_media/bin:bookworm:amd64:dicaffeine-0.7.3-linux.deb
> 
> After the successful installation please run automatic script to download the NDI libraries: `sudo dicaffeine_get_ndi5 install x86_64-linux-gnu`
> 
> The packages are **untested**, so I am not sure if everything works as it should. I'll do more extensive tests later.
> 
> PS: user has to be allowed to use sudo 😉

I could not get Dicaffeine to run via the website instructions until I ran this `install` command. After that, it works a treat. Thanks!
