### ISSUE TITLE
fps of received video

### ISSUE THREAD

**Issue by athakrar1** [melnijir/Dicaffeine#51]
What is the maximum fps with which the NDI Player can render frames? How do I measure the fps at which my video is received & rendered?

**Comment by melnijir** [comment]
Hi, maximal FPS can be defined in the config file by editing the _max_framerate_ value:

`/etc/dicaffeine/dserver.json`

this applies for the **Dicaffeine >= 0.7.4**.

To check the fps please refer to the Dicaffeine guide:

https://dicaffeine.com/guide#dicaffeine_with_yuri2

fps should be visible in the console output.
