### ISSUE TITLE
Multicast

### ISSUE THREAD

**Issue by jchoy-ct** [melnijir/Dicaffeine#52]
I’m having issues with Multicast at the moment. Tested with NDI monitor on other machines and the multicast setup is working correctly. Raspi just shows a black screen. Disabled multicast in NDI Access Manager and Raspi works as intended. Is this a known issue or unsupported at the moment or am I missing something? Thanks for your help!

Forgot to mention I’m using a pi 4 model B and I’ve tested using both 32-bit Buster and 64-bit Bullseye.

**Comment by melnijir** [comment]
Sorry, this depends on NewTek's NDI libraries, Dicaffeine uses them to lookup/receive the NDI stream. It's a thing a cannot change.
