### ISSUE TITLE
Audio and Video frequently drops on Raspbery Pi 4

### ISSUE THREAD

**Issue by shewitson-spt93** [melnijir/Dicaffeine#53]
- Running latest version of Dicaffeine
- Using Simple mode, Main stream only, low resolution. Plugged into monitor set to 1152x864.
- Raspberry Pi is 2gb variant (running Bullseye)
- Using wifi connection
- NDI tools Screen Capture for NDI source
- RPi has got a heatsink and official power supply
- Temperature remains below 40degC. Load is around 20%

Using bashtop I can see that the network traffic is dropping periodically. When it is working, bashtop reports ~2.0 MiB/s.

![bashtop](https://github.com/melnijir/Dicaffeine/assets/74405080/1e805fda-e666-4a9b-9e4a-887108d4f278)

Interestingly, I've got a RaspberryPi 3B+ and the signal isn't dropping out.

**Comment by melnijir** [comment]
Hi, it can be two things - classic NDI works much better on a wired network and depending on the source, there can be slow color conversion which is done on a graphics card and you won't see it as a CPU usage.

**Comment by shewitson-spt93** [comment]
Unsure why the RPi3b works fine, but I'll just use that in future. Thanks
