### ISSUE TITLE
Update to latest Raspian OS (Debian 12) and H.265 for ScreenCapture HX

### ISSUE THREAD

**Issue by IndexOutOfMJ** [melnijir/Dicaffeine#56]
Hey, 
if possible could you please update your software to the latest standards and support Screen Capture HX?
That would be great ^^

**Comment by melnijir** [comment]
Hey,
please try the new beta:
https://dicaffeine.com/raspbian

should be working on the RPi OS Debian Bookworm 64bit. Still missing some features, but it should be ready to use for basic playback/streaming with NDI-HX support.
