### ISSUE TITLE
Ubuntu install not working.

### ISSUE THREAD

**Issue by markbrill** [melnijir/Dicaffeine#57]
Hi - following the instructions for the install for the ubuntu image. 1.) the update in gpg key storage poses a hurdle for istall, took some google fu to overcome. (the key process needs an update please.) Once this is over come the *.list file points to nothing and returns E:\unable to locate file (or words to that effect) was installing for ubuntu 22.04 on arm.

**Comment by melnijir** [comment]
Hi, it's written in the installation description "Ubuntu LTS 22.04/20.04 on Intel/AMD", so no Ubuntu on arm is currently supported. If you want to use the Dicaffeine on Raspberry, please refer to https://dicaffeine.com/raspbian manual.
