### ISSUE TITLE
No video over Wifi

### ISSUE THREAD

**Issue by GertjanBiasino** [melnijir/Dicaffeine#58]
Hi,

I installed Dicaffeine in order to use it for wireless video over NDI. But after installing i nothing came trough. The stream was recognised but no frames where send. It works fine using a cable.

I had a look in the issues and in Issue "Unable to view webcam stream on separate machine #47" and Black screen after hitting play #48

I can see there are problems using wifi. But i can't seem to find a way to get it working on wifi. Is it possible to use it wireless?

**Comment by nettings** [comment]
No.

**Comment by melnijir** [comment]
Classic NDI over Wifi is not supported.
