### ISSUE TITLE
Disable Dicaffeine without uninstalling

### ISSUE THREAD

**Issue by alessionossa** [melnijir/Dicaffeine#6]
I have a Raspberry Pi that I reuse for different use cases, based on what I need. Sometimes I want to disable Dicaffeine to free up port 80 for other uses, but the only option at the moment seems to be uninstalling it completely.

**Comment by melnijir** [comment]
Hi, you can use systemctl command:
`systemctl --user disable dicaffeine`
but be careful, service will be re enabled with every update.
