### ISSUE TITLE
Raspberry Pi 5 support, and performance benchmarks?

### ISSUE THREAD

**Issue by amcjen** [melnijir/Dicaffeine#60]
Hey there!

Love the project, and curious when (or if) you might have your hands on a RaspPi5 to see how the framerate does on the new hardware. 

I realize they're basically unobtainable right now, but happy to help sponsor one over to you if it helps accelerate!

**Comment by melnijir** [comment]
Hey,

try the new beta: https://dicaffeine.com/raspbian

it should work on the new RPi OS with RPi5. I've done just a few tests but the framerates were quite impressing!

**Comment by amcjen** [comment]
Wonderful! I don't have Rpi5 on-hand. Any ideas of what initial framerates/resolutions you're seeing in your initial tests?
