### ISSUE TITLE
Raspberry installation fails

### ISSUE THREAD

**Issue by dontpanic84** [melnijir/Dicaffeine#62]
I get this error when trying to install on a Raspberry Pi 4: 

E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by brainey** [comment]
I get the same error. Here is more of the output:
`# dpkg --configure dicaffeine
Setting up dicaffeine (0.6.3) ...
chown: cannot access '/etc/dhcpcd.conf': No such file or directory
dpkg: error processing package dicaffeine (--configure):
 installed dicaffeine package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 dicaffeine
`
Other than installing dhcpcd, does anyone have a work around for this problem ?

**Comment by melnijir** [comment]
You're probably using the new Raspberry Pi OS bookworm - packages for the newest distribution will be ready to download in a few days. Currently only older bullseye version is supported.
