### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by pinpox** [melnijir/Dicaffeine#64]
Hey, I was looking for instructions on how to compile this for NixOS as I would like to package it. Are there any instructions on how to build this software on other OS's apart from Raspian? Would be very nice to be able to use it on other linux distors as I couldn't find anything else to stream a usb webcam over ndi

**Comment by melnijir** [comment]
Hi, you can compile Dicaffeine branch of libyuri:

https://github.com/melnijir/libyuri/tree/dicaffeine

and stream webcam using the command line, some examples can be found on the official pages:

https://dicaffeine.com/guide
