### ISSUE TITLE
Is a GUI required to run?

### ISSUE THREAD

**Issue by jnpetersen** [melnijir/Dicaffeine#66]
I'm trying to setup Dicaffeine on a NUC style device.  I've tested with the original install of the OS (which has a GUI) and I want to make the system as minimal as possible, so I was wondering if a desktop is required for this to work?

**Comment by melnijir** [comment]
Hi, it's not if you're fine with the command line tools. You can compile Yuri2 binary which serves as a backend for the Dicaffeine. Short guide how to use it and how to compile the Yuri2 binary is here:

https://dicaffeine.com/guide

**Comment by OscarParzon** [comment]
Hello! My English is very bad! I want to understand correctly: Is it not necessary to use a desktop?
For me it is much better to use without a desktop, for example: a RPi without a monitor. I don't want the desktop.
Excuse me for the new question, but your answer leaves me with some doubts when translating. ;)
