### ISSUE TITLE
Audio Only NDI

### ISSUE THREAD

**Issue by tommygothamwest** [melnijir/Dicaffeine#68]
I'm sending an audio-only NDI signal from a Mackie DLZ Creator to DiCaffeine. For the sake of resource management, does DiCaffeine generate a video when playing this out (we have the audio signal going out of the 1/8" audio jack on a RPi4)?

**Comment by melnijir** [comment]
Hi, it should generate an empty video output, it should consume only a little resources on the RPi4.
