### ISSUE TITLE
Custom port for webserver

### ISSUE THREAD

**Issue by alessionossa** [melnijir/Dicaffeine#7]
I want to run a webserver and Dicaffeine on the same machine, but Dicaffeine binds to port 80 and as far as I know there is no way to change this.
I want, for example, to access Dicaffeine web interface on port 8080.

**Comment by ammartist** [comment]
+1

**Comment by melnijir** [comment]
Hi, it should be possible via the config file:
`/etc/dicaffeine/dserver.json`
and restarting the dicaffeine service:
`systemctl --user restart dicaffeine`

Unfortunately it's not persistent across the updates (I'll fix that) and there is a second port 9192 the Dicaffeine is using for PTZ control and it currently cannot be changed.
