### ISSUE TITLE
pi dicaffeine.service not found

### ISSUE THREAD

**Issue by ivan-ef** [melnijir/Dicaffeine#71]
**raspberry pi - bookworm**

`dicaffeine_get_ndi5 install aarch64-rpi4-linux-gnueabi`

**curl: (22) The requested URL returned error: 403**

By the way, how does rpi 5 perform compared to 4?

**Comment by melnijir** [comment]
Hi, wasn't that a temporary problem? I've just tried the same command on the fresh installation and it worked fine.

With RPi5 I am able to play 1080p50 videos without frame drops, also streaming (at least 1080p30) was working.

**Comment by jacobcperez15** [comment]
Hi, this issue seems to be back with a new error message when running `dicaffeine_get_ndi5 install aarch64-rpi4-linux-gnueabi`:
"curl: (22) The requested URL returned error: 530"

I followed your instructions using a fresh install of bookworm. I'm using a rpi4.
